name: Security
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read
jobs:
  govuln:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: vulncheck
      uses: golang/govulncheck-action@v1
      with:
        go-version-input: 1.24.4
        go-package: ./...